## 开发环境
server:
  address: 0.0.0.0
  port: 9093
  tomcat:
    max-http-form-post-size: 13MB

## 据源配置
spring:
  ## thymeleaf 配置
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-g7jdk2y0.sql.tencentcdb.com:63676/e_archives_private
    username: artemis
    password: Q!w2e3r4t5Y^

## Mybatis
mybatis:
  mapper-locations: classpath:cn/zealon/**/mapper/*.xml