
server:
  tomcat:
    uri-encoding: UTF-8

# 数据库设置
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password=
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000

    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 20
        #连接池中的最小空闲连接，默认值也是0。
        min-idle: 5
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-wait: 2000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-active: 1000
