
spring:
  activemq:
    broker-url: tcp://47.104.241.41:61616
    #mq账户密码
    user: admin
    password: pass123

    #mq连接池
    pool:
      enabled: true
      max-connections: 10
  jms:
    listener:
      acknowledge-mode: CLIENT