server:
  port: 8080

spring:
  ## thymeleaf \u914D\u7F6E
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass123

## Mybatis
mybatis:
  mapper-locations: classpath*:mappers/*.xml



## \u5206\u9875\u914D\u7F6E
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
