server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/space_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Pass123.com
